Ejada/urls.py
from django.contrib import admin
from django.urls import path
from deal_app import views as deal_app_views
from user_app import views as user_app_views
from django.conf.urls import include

urlpatterns = [
    path(r'', user_app_views.index ,name='index',),
    path(r'deal_app/',include('deal_app.urls')),
    path(r'user_app/',include('user_app.urls')),
    path('admin/', admin.site.urls),
    path(r'logout/',user_app_views.user_logout,name='logout'),
    path(r'special/',user_app_views.special,name='special'),

## there is two way to create links
    path(r'sign_up/',user_app_views.sign_up,name='sign_up'),
]

deal_app/urls.py
from deal_app import views
from django.conf.urls import url


app_name = 'deal_app'
urlpatterns=[
    url(r'^main/',views.main,name='main'),
    url(r'^new_deal/',views.new_deal,name='new_deal'),
    url(r'^customers/',views.customers,name='customers'),
    url(r'^customers_submission/',views.customer_submit_his_deal,name='customers_submission'),
]

user_app/urls.py
from user_app import views
from django.conf.urls import url

app_name = 'user_app'

urlpatterns=[
    url(r'^sign_up/',views.sign_up,name='sign_up'),
    url(r'^index/',views.index,name='index'),
    url(r'^user_login/',views.user_login,name='user_login')
    #url(r'other/',views.other,name='other')
]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

'''
class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=20)
    phone = models.CharField(max_length=30)

    def __str__(self):
        return self.name
'''
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User , on_delete= models.CASCADE)

    #additional info

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pic',blank=True)
    def __str__(self):
        return self.user.username

user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_app.models import UserProfileInfo



from user_app.models import User


class User_Form(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
#    name = forms.CharField()
#    email = forms.EmailField()
#    password = forms.CharField()
#    phone = forms.CharField()

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


    #text = forms.CharField(widget = forms.Textarea)

user_app/views.py
from django.shortcuts import render
#from . import forms
from user_app.forms import User_Form,UserProfileInfoForm

# Login Import
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'user_app/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    #return HttpResponseRedirect('user_app/index')
    return render(request,'user_app/index.html')

def sign_up(request):

    registered = False

    ##form = User_Form()
    if request.method == 'POST':
        user_form = User_Form(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit =False)
            profile.user = user

            if 'profile_pic' is request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()
            registered= True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = User_Form()
        profile_form = UserProfileInfoForm()


    return render(request, 'user_app/sign_up.html',
                    {'user_form':user_form, 'profile_form':profile_form,'registered':registered})




def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone tried to login and failed")
            print("Username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request, 'user_app/login.html',{})

templates/user_app/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

.
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top navbar-expand-lg">

      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{%url 'index' %}"><strong>Ejada</strong> </a> </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'admin:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{%url 'deal_app:index' %}">Tableau Deals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'user_app:sign_up'%}">sign_up</a>
          </li>
        </ul>


      </div>
    </nav>

    <div class="container">
      {%block body_block%}
      {% endblock%}

    </div>
  </body>
</html>

templates/user_app/index.html
{% extends "basic.html"%}

{% block body_block%}


    <h1> welcome from index user_app</h1>


{% endblock%}

templates/user_app/login.html
{% extends "basic.html"%}

{% block body_block%}


    <div class="jumbotron">
      <h1> Please Login</h1>
      <form  action="{% url 'user_app:user_login'%}" method="post">
        {%csrf_token%}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">
      </form>

    </div>


{% endblock%}

templates/user_app/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>hi from other page</h1>
  </body>
</html>

templates/user_app/sign_up.html
{% extends "basic.html"%}

{% block body_block%}



    <div class="container">
      {%if registered %}
        <h1>Thanks, You alredy registered</h1>
      {% else %}

        <h3>Fill out the form please</h3>
        <form method="POST">
          {{user_form.as_p}}
          {{profile_form.as_p}}

          {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Register">
        </form>
      {%endif%}
    </div>


{% endblock%}