Ejada/urls.py
from django.contrib import admin
from django.urls import path
from deal_app import views as deal_app_views
from user_app import views as user_app_views
from django.conf.urls import include

urlpatterns = [
    path(r'', user_app_views.index ,name='index',),
    path(r'deal_app/',include('deal_app.urls')),
    path(r'user_app/',include('user_app.urls')),
    path('admin/', admin.site.urls),
    path(r'logout/',user_app_views.user_logout,name='logout'),
    path(r'special/',user_app_views.special,name='special'),

## there is two way to create links
    path(r'sign_up/',user_app_views.sign_up,name='sign_up'),
]

deal_app/urls.py
from deal_app import views
from django.conf.urls import url


app_name = 'deal_app'
urlpatterns=[
    url(r'^main/',views.main,name='main'),
    url(r'^new_deal/',views.new_deal,name='new_deal'),
    url(r'^customers/',views.customers,name='customers'),
    url(r'^customers_submission/',views.customer_submit_his_deal,name='customers_submission'),
]

user_app/urls.py
from user_app import views
from django.conf.urls import url

app_name = 'user_app'

urlpatterns=[
    url(r'^sign_up/',views.sign_up,name='sign_up'),
    url(r'^index/',views.index,name='index'),
    url(r'^user_login/',views.user_login,name='user_login')
    #url(r'other/',views.other,name='other')
]

templates/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

.
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top navbar-expand-lg">

      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{%url 'index' %}"><strong>Ejada</strong> </a> </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Our Customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          {%if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">HR System</a><!--ADD TIMESHEET - Vacation Request using Dropdown list-->
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Travel System</a><!--ADD apply request - booking tickets - and expense claim - and approval from manager  using Dropdown list-->
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{%url 'deal_app:main' %}">Tableau Deals</a>
          </li>
          <li> <a class="navbar-link" href="{% url 'logout'%}">Logout</a></li>
          {%else%}
          <li> <a class="navbar-link" href="{% url 'user_app:user_login'%}">Login</a></li>
          <li class="nav-item" style="float:right">
            <a class="nav-link" href="{%url 'user_app:sign_up'%}">Sign Up</a>
          </li>
          {%endif%}
        </ul>
      </div>
    </nav>


    <div class="container">
      {%block body_block%}
      {% endblock%}

    </div>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>my first page</title>
  </head>
  <body>
    <ul>
      <li><a class="active" href="#home">Home</a></li>
      <li><a href="#news">News</a></li>
      <li><a href="#contact">Contact</a></li>
      <li style="float:right"><a href="#about">About</a></li>
    </ul>

    <h1> Hello from my first HTML page  </h1>

  </body>
</html>