Ejada/urls.py
from django.contrib import admin
from django.urls import path
from deal_app import views as deal_app_views
from user_app import views as user_app_views
from django.conf.urls import include

urlpatterns = [
    path(r'', user_app_views.index ,name='index',),
    path(r'deal_app/',include('deal_app.urls')),
    path(r'user_app/',include('user_app.urls')),
    path('admin/', admin.site.urls),
    path(r'logout/',user_app_views.user_logout,name='logout'),
    path(r'special/',user_app_views.special,name='special'),

## there is two way to create links
    path(r'sign_up/',user_app_views.sign_up,name='sign_up'),
]

deal_app/urls.py
from deal_app import views
from django.conf.urls import url


app_name = 'deal_app'
urlpatterns=[
    url(r'^main/',views.main,name='main'),
    url(r'^new_deal/',views.new_deal,name='new_deal'),
    url(r'^customers/',views.customers,name='customers'),
    url(r'^customers_submission/',views.customer_submit_his_deal,name='customers_submission'),
]

deal_app/models.py
from django.db import models

# Create your models here.


class Customer(models.Model):
    name = models.CharField(max_length=100)
    appreviation = models.CharField(max_length=15)
    country = models.CharField(max_length=30)
    region = models.CharField(max_length=30)
    lob = models.CharField(max_length = 30)
    def __str__(self):
        return self.name


## Customer - Ejada info - Summary file: EjadacColumns=e_ , CustomerColumns= c_, generaLColumns= g_
class Deal(models.Model):

    ## general columns
    name = models.CharField(max_length = 20)
    ## one to many relation
    customer = models.ForeignKey(Customer,on_delete=models.PROTECT)

    creation_date =models.DateField()
    date_lastupdated = models.DateField(auto_now=True)
    status = models.CharField(max_length = 20) ##in progress or win or loss

    ## Ejada columns to be used in summary file
    status_descriptian = models.TextField()
    deal_source = models.CharField(max_length=50)
    third_party = models.CharField(max_length=50)
    project= models.CharField(max_length=50)
    margin_type = models.CharField(max_length=50)
    new_renew = models.CharField(max_length=10)
    sub_perpcual = models.CharField(max_length=50)



    ## Customer fields to be added by himself


    def __str__(self):
        return self.name


class Deal_Items_Price_Lookup(models.Model):
    creator_on_prem_price_per_month_dollar = 70
    creator_on_prem_price_per_month_dollar = 0
    explorer_on_prem_price_per_month_dollar = 0
    viewer_on_prem_price_per_month_dollar = 0
    term_desktop_personal_price_per_month_dollar = 0
    term_desktop_professional_price_per_month_dollar = 0
    term_server_core_price_per_month_dollar = 0
    term_server_interactor_price_per_month_dollar = 0
    tableau_online_price_per_month_dollar = 0
    server_management_price_per_month_dollar = 0
    creator_online_price_per_month_dollar = 0
    explorer_online_price_per_month_dollar = 0
    viewer_online_price_per_month_dollar = 0
    perpetual_desktop_personal_price_per_month_dollar = 0
    perpetual_desktop_professinal_price_per_month_dollar = 0
    perpetual_server_core_price_per_month_dollar = 0
    perpetual_server_interactor_price_per_month_dollar = 0
    data_management_online_price_per_month_dollar = 0
    data_management_on_premise_price_per_month_dollar = 0
    def __str__(self):
        return self.name

class Deal_Items(models.Model):
    name = models.CharField(max_length = 20)
    ## one to many relation
    deal = models.ForeignKey(Deal,on_delete = models.CASCADE)
    ## one to one relation
    deal_price = models.OneToOneField(Deal_Items_Price_Lookup,on_delete= models.CASCADE)

    creator_on_prem = models.BooleanField(default= False)
    explorer_on_prem = models.BooleanField(default= False)
    viewer_on_prem = models.BooleanField(default= False)
    term_desktop_personal = models.BooleanField(default= False)
    term_desktop_professional = models.BooleanField(default= False)
    term_server_core = models.BooleanField(default= False)
    term_server_interactor = models.BooleanField(default= False)
    tableau_online = models.BooleanField(default= False)
    server_management = models.BooleanField(default= False)
    creator_online = models.BooleanField(default= False)
    explorer_online = models.BooleanField(default= False)
    viewer_online = models.BooleanField(default= False)
    perpetual_desktop_personal = models.BooleanField(default= False)
    perpetual_desktop_professinal = models.BooleanField(default= False)
    perpetual_server_core = models.BooleanField(default= False)
    perpetual_server_interactor = models.BooleanField(default= False)
    data_management_online = models.BooleanField(default= False)
    data_management_on_premise = models.BooleanField(default= False)
    def __str__(self):
        return self.name

deal_app/forms.py
from django import forms
from deal_app.models import Deal


class Deal_Form(forms.ModelForm):

    class Meta():
        model = Deal
        fields = '__all__'

    #text = forms.CharField(widget = forms.Textarea)

deal_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from deal_app.models import Customer, Deal
from deal_app.forms import Deal_Form

# Create your views here.

def index(request):
    ##return HttpResponse("<em>Hello World!</em>")
    #my_dic ={'insert_me':2+3   }
    deals = Deal.objects.all()
    deals_dictionary = {'deals': deals}
    return render(request, 'deal_app/index.html', context=deals_dictionary)



def main(request):
    deals = Deal.objects.all()
    deals_dictionary = {'deals': deals}
    return render(request,'deal_app/main.html', context=deals_dictionary)


def customers(request):
    customers = Customer.objects.raw('select * from deal_app_customer')
    number_of_deals = Deal.objects.raw('select count(id) from deal_app_deal group_by name')
    return render(request,'deal_app/customers.html',context = {'customers':customers,'number_of_deals':number_of_deals})





def new_deal(request):

    #form = forms.User_Form()
    form = Deal_Form()
    if request.method == 'POST':
        form = Deal_Form(request.POST)

        if form.is_valid():
            form.save()
            return main(request)
        else:
            print('error in view.py deal_app')
    return render(request, 'deal_app/add_new_deal.html', {'form':form})


## the page that the customer can submit his requiest by himself to send him the quotation automatic
def customer_submit_his_deal(request):

    #form = forms.User_Form()
    form = Deal_Form()
    if request.method == 'POST':
        form = Deal_Form(request.POST)

        if form.is_valid():
            form.save()
            return main(request)
        else:
            print('error in view.py deal_app')
    return render(request, 'deal_app/first_step_customer_submit_his_deal.html', {'form':form})

templates/deal_app/add_new_deal.html
{% extends "basic.html"%}

{% block body_block%}


<div class="container">
  <form method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Add New Deal">
  </form>
</div>


{% endblock%}

templates/deal_app/customers.html
{% extends "basic.html"%}

{% block body_block%}


<div class="container">
  <form method="POST">
    <h3>to do list:</h3>
      <h4>Analysis for each customers</h4>
      <h5>- Customer name</h5>
      <h5>- Numebr of deals</h5>
      <h5>- Total amount customer paid</h5>
      <h5>- Total profit</h5>
    {%for customer in customers%}
        {{customer.name}}
        {{deal.name.number_of_deals}}
    {%endfor%}
  </form>
</div>


{% endblock%}

templates/deal_app/first_step_customer_submit_his_deal.html
{% extends "basic.html"%}

{% block body_block%}
 to do list: add form here

{% endblock%}

templates/deal_app/main.html
{% extends "basic.html"%}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

{% block body_block%}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <h6> welcome from Deal app main</h6>
    <div class="container">
      <input type="submit" class="btn btn-primary" value="Register">
      <a  href="{%url "deal_app:customers"%}}">Our Customers</a>
      <a  href="{%url "deal_app:new_deal"%}}">Add New</a>
      <a  href="{%url "deal_app:customers_submission"%}}">Customer can submit his request </a>
    </div>

<div class="container">


    <table class="table table-striped table-dark">
      <thead  class="thead-dark">
        <tr>

            <th scope="col">customer</th>
            <th scope="col">creation_date</th>
            <th scope="col">date_lastupdated</th>
            <th scope="col">status</th>
            <th scope="col">status_descriptian</th>
            <th scope="col">deal_source</th>
            <th scope="col">third_party</th>
            <th scope="col">project</th>
            <th scope="col">margin_type</th>
            <th scope="col">new_renew</th>
            <th scope="col">sub_perpcual</th>

        </tr>
      </thead>
      <tbody>
        {% for deal in deals %}
        <tr>
            <td><a  href="#">{{ deal.customer }}</a></td>
            <td>{{ deal.creation_date }}</td>
            <td>{{ deal.date_lastupdated }}</td>
            <td>{{ deal.status }}</td>
            <td>{{ deal.status_descriptian }}</td>
            <td>{{ deal.deal_source }}</td>
            <td>{{ deal.third_party }}</td>
            <td>{{ deal.project }}</td>
            <td>{{ deal.margin_type }}</td>
            <td>{{ deal.new_renew }}</td>
            <td>{{ deal.sub_perpcual }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
{% endblock%}